version: '3.9'
services:
  backend:
    image: ghcr.io/dascr/dascr-board/dascr-board-svc:main
    ports:
      - "7000:7000"
    environment:
      - API_IP=0.0.0.0
      - API_PORT=7000
    networks:
      - dascr
  frontend:
    depends_on:
      - backend
    image: ghcr.io/dascr/dascr-board/dascr-board-ui:main
    ports:
      - "7070:7070"
    environment:
      - VITE_API_BASE=http://localhost:7000/
      - VITE_API_URL=http://localhost:7000/api
      - VITE_WS_URL=ws://localhost:7000/ws
    networks:
      - dascr

networks:
  dascr:
    name: dascr
